name: doc_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.4+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.20.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  package_info_plus: ^8.3.0
  logger: ^2.5.0
  device_preview: ^1.2.0
  open_file: ^3.5.10
  flutter_markdown: ^0.7.7
  path_provider: ^2.1.5
  dynamic_path_url_strategy: ^1.0.0
  permission_handler: ^12.0.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2

  # Web Specific Packages
  http: ^1.3.0
  data_table_2: ^2.5.18

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  #Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  liquid_pull_to_refresh: ^3.0.1
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Local Assets
  assets:
    - assets/logos/
    - assets/images/animations/
    - assets/images/content/
    - assets/icons/payment_methods/
    - assets/icons/


  # Local Fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 800